### PR TITLE
Added C++ code for Mirror of a Binary Tree

### PR DESCRIPTION
**Pull request by alkatrivedi**
Implementation in C++ to find the Mirror of a Binary Tree using queue. Thank you!

### CODE REVIEW

**Comment by shreyanshchordia** [comment]
Hey since this is an iterative solution I request you to change the name of the file to 

`Mirror Of Tree Iterative Approach.cpp`

Or even if some other name but explicitly mention Iterative so that someone else can add solution for the recursive approach.

Once that done, I will merge your PR.

**Comment by alkatrivedi** [comment]
Done that. Can you please check it?

**Comment by alkatrivedi** [comment]
Thanks for merging:)

**Comment by shreyanshchordia** [comment]
You're welcome :))

**Pull request merged**
