### PR TITLE
Added threaded binary tree implementation in CPP

### PR DESCRIPTION
**Pull request by vaishnavirshah**
### Threaded binary tree are uses to make faster inorder traversal without using stack or recursion.
It stores the inorder successor, if the right node is empty.
And stores the inorder predecessor if left node is empty.

- There are functions to add, delete and search for an element.
- Also the inorder for the tree.

This is in relation to the issue #12

### CODE REVIEW

**Comment by shreyanshchordia** [comment]
Please add description of what exactly a threaded Binary Tree is, in the comments of the code.

**Comment by vaishnavirshah** [comment]
@shreyanshchordia Added the comments in the code.

**Comment by shreyanshchordia** [comment]
I read an article about threaded Binary Tree. But your code doesn't represent the similar structure. Correct me if I am wrong. But I have read this [article](https://www.geeksforgeeks.org/threaded-binary-tree/amp/) according to which a threaded Binary Tree is one in which a NULL right pointer is made to point to the inorder successor (if successor exists)

**Comment by vaishnavirshah** [comment]
The code which i have written is for double threaded binary tree in which a NULL right pointer is made to point to the inorder successor and NULL left pointer is made to point to the inorder predecessor. 
My representation will be similar to [this](https://www.geeksforgeeks.org/double-threaded-binary-search-tree/).
However the link which you have attached is for single threaded binary tree in which a NULL right pointer is made to point to the inorder successor.

**Comment by vaishnavirshah** [comment]
Thank you 👍

**Pull request merged**
