### PR TITLE
added by abhinav jain

### PR DESCRIPTION
**Pull request by abhinavjain20**
Hi,
I added an optimized solution for the diameter of the binary tree.

### CODE REVIEW

**Comment by abhinavjain20** [comment]
Hi,
Added optimized solution for balanced binary Tree.

**Comment by shreyanshchordia** [comment]
Please add the codes in C++ folder. If you have optimized the code then remove the code that is already present in the C++ folder and replace it with your code.

**Comment by abhinavjain20** [comment]
Replaced.

**Comment by shreyanshchordia** [comment]
Delete Optimized folder

**Pull request closed without merging**
